/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/arm_full.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Humerus002.geometry} material={materials.Bone} />
      <mesh geometry={nodes.Humerus002_1.geometry} material={materials.NewCartilage} />
      <mesh geometry={nodes.Radius002.geometry} material={materials.Bone} />
      <mesh geometry={nodes.Radius002_1.geometry} material={materials.NewCartilage} />
      <mesh geometry={nodes.Ulna002.geometry} material={materials.Bone} />
      <mesh geometry={nodes.Ulna002_1.geometry} material={materials.NewCartilage} />
      <mesh geometry={nodes.Long_head_of_biceps_brachii001.geometry} material={materials.Muscle} />
      <mesh geometry={nodes.Long_head_of_biceps_brachii001_1.geometry} material={materials.Tendon} />
      <mesh geometry={nodes.Short_head_of_biceps_brachii001.geometry} material={materials.Muscle} />
      <mesh geometry={nodes.Short_head_of_biceps_brachii001_1.geometry} material={materials.Tendon} />
      <mesh geometry={nodes.Brachialis_muscle_1.geometry} material={materials.Muscle} />
      <mesh geometry={nodes.Brachialis_muscle_2.geometry} material={materials.Tendon} />
      <mesh geometry={nodes.Lateral_head_of_triceps_brachii001.geometry} material={materials.Muscle} />
      <mesh geometry={nodes.Lateral_head_of_triceps_brachii001_1.geometry} material={materials.Tendon} />
      <mesh geometry={nodes.Long_head_of_triceps_brachii001.geometry} material={materials.Muscle} />
      <mesh geometry={nodes.Long_head_of_triceps_brachii001_1.geometry} material={materials.Tendon} />
      <mesh geometry={nodes.Medial_head_of_triceps_brachii001.geometry} material={materials.Muscle} />
      <mesh geometry={nodes.Medial_head_of_triceps_brachii001_1.geometry} material={materials.Tendon} />
      <mesh geometry={nodes.Radial_collateral_ligament.geometry} material={materials.Ligament} position={[-0.32, 0.07, 0.08]} rotation={[-Math.PI / 2, 0, 0.15]} scale={12.67} />
      <mesh geometry={nodes.Ulnar_collateral_ligament.geometry} material={materials.Ligament} position={[0.19, 0.21, 0.11]} rotation={[-Math.PI / 2, 0, 0.15]} scale={12.67} />
    </group>
  )
}

useGLTF.preload('/arm_full.glb')
