/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/bone_marrow.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Humerus_1.geometry} material={nodes.Humerus_1.material} />
        <mesh geometry={nodes.Humerus_2.geometry} material={nodes.Humerus_2.material} />
      </group>
      <mesh geometry={nodes.Humerus002.geometry} material={materials['Bone.002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-0.08, -0.01, -0.43]} scale={[0.56, 0.56, 0.01]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[-0.03, 0, -1.14]} scale={[1, 1, 0.01]} />
      <mesh geometry={nodes.Inside001.geometry} material={materials['Marrow.003']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/bone_marrow.glb')
